apiVersion: v1
kind: ServiceAccount
metadata:
  name: minecraft-restarter
  namespace: minecraft
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minecraft-restarter-role
  namespace: minecraft
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minecraft-restarter-binding
  namespace: minecraft
subjects:
  - kind: ServiceAccount
    name: minecraft-restarter
    namespace: minecraft
roleRef:
  kind: Role
  name: minecraft-restarter-role
  apiGroup: rbac.authorization.k8s.io
